export const post = [
  {
    id: 1,
    slug: 'lorem-ipsum-dolor-sit-amet',
    title: 'Lorem Ipsum Dolor Sit Amet',
    category: 'technology',
    author: 'Valentino Jurken',
    body: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut justo nisl, eleifend eu ex quis, pharetra pharetra ante. Proin sodales ligula sit amet lectus sodales, a sodales justo tincidunt. Etiam dapibus mollis turpis at luctus. Phasellus commodo pretium egestas. Vivamus euismod id lectus eget malesuada. Phasellus lacinia arcu sed ex ornare porttitor. Vivamus porta dui a massa auctor facilisis. Vivamus at risus urna.',
  },
  {
    id: 2,
    slug: 'Nullam-Tellus-Ex-Malesuada-ac',
    title: 'Nullam Tellus Ex Malesuada ac',
    category: 'technology',
    author: 'Valentino Jurken',
    body: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eget auctor mauris. Nullam odio eros, molestie in varius a, tempus quis risus. Nunc velit tortor, consectetur a vulputate et, pulvinar et elit. Sed nec ornare mauris, quis pharetra ante. Ut turpis augue, commodo vitae dolor at, ornare viverra diam. Suspendisse bibendum magna erat. Proin tempus, ante in tincidunt blandit, quam erat dictum justo, cursus sodales ex augue non est. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vel rutrum risus, vel aliquam neque. Nam a massa elementum, ultricies tellus vel, congue enim.',
  },
  {
    id: 3,
    slug: 'mari-belajar-ux-writing-tipis-tipis',
    title: 'Mari belajar UX Writing tipis tipis',
    category: 'design',
    author: 'Romaguera Arile',
    body: 'Belajar UX Writing dari mengamati copy atau tulisan pada judul landing page dari website perusahaan teknologi lalu mencoba menerapkan pada design yang sedang dibuat.',
  },
  {
    id: 4,
    slug: 'cara-memakai-inspirasi-dari-referensi',
    title: 'Cara memakai inspirasi dari referensi',
    category: 'tips',
    author: 'Patricia Romanova',
    body: 'Bagaimana cara menggunakan referensi pada design yang sedang dikerjakan?" "Bagaimana menggunakan inspirasi dari referensi biar jatuh nya enggak menjiplak?',
  },
  {
    id: 5,
    slug: 'proses-design-dalam-pembuatan-data-visual',
    title: 'Proses design dalam pembuatan data visual',
    category: 'design',
    author: 'Patricia Romanova',
    body: 'Data Visualization bukan hanya menampilkan angka ataupun data, tapi juga menyampaikan sebuah cerita kepada mereka yang membacanya',
  },
  {
    id: 6,
    slug: 'proses-membuat-layout-dan-komposisi-pada-ui-design',
    title: 'Proses membuat layout dan komposisi pada UI Design',
    category: 'design',
    author: 'Nicolas Kurtis',
    body: 'Beberapa langkah dalam membuat komposisi dan layout secara bertahap dan memastikan semua komponen dan fungsionalitas yang dibutuhkan lengkap',
  },
  {
    id: 7,
    slug: 'dari-website-programmer-menjadi-ui-designer',
    title: 'Dari Website Programmer Menjadi UI Designer',
    category: 'desing',
    author: 'Don Quixote Doflaminggo',
    body: 'Jika ingin pindah jadi UI Designer, jangan lepaskan profesi yang sekarang, tetap jalani sambil belajar tentang UI Design. Perlahan kamu akan tahu, apakah UI Design ini passion atau pelarian',
  },
  {
    id: 8,
    slug: 'kutipan-designer-yang-bisa-menambah-cara-pandang',
    title: 'Kutipan designer yang bisa menambah cara pandang',
    category: 'design',
    author: 'Don Quixote Doflaminggo',
    body: 'Beberapa kutipan di artikel ini sangat membantu saya saat membuat design. Membantu berpikir dan mempertimbangkan hal hal yang harus diperhatikan.',
  },
  {
    id: 9,
    slug: 'yang-disiapkan-untuk-handover-file',
    title: 'Yang disiapkan untuk handover file design website ke developer',
    category: 'tips',
    author: 'Romaguera Arile',
    body: 'UI/UX tidak hanya tentang memudahkan user atau pengguna tapi juga memudahkan rekan kerja seperti developer. Berikut beberapa hal yang bisa membantu mereka.',
  },
  {
    id: 10,
    slug: 'belajar-bikin-copy-sendiri',
    title: 'Dear UI Designer, yok bisa yok belajar bikin copy sendiri',
    category: 'tips',
    author: 'Patricia Romanova',
    body: 'Lupakan sejenak Lorem Ipsum saat mengisi teks pada design UI mu. Coba buat copy mu sendiri. Buat rekan kerja UX Writer lebih happy saat bekerja.',
  },
];
